spring:
  datasource:
    password: King1234.
    username: root
    url: jdbc:mysql://127.0.0.1:3306/m2
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: m2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 6060
